'use client'

import { ShieldCheck } from 'lucide-react'

interface VerifiedReportBadgeProps {
  scanId: string
  compact?: boolean
}

export default function VerifiedReportBadge({ scanId, compact = false }: VerifiedReportBadgeProps) {
  // Generates a mock but realistic-looking hash from the scanId
  const hash = Array.from(scanId || 'zynthsecure')
    .reduce((acc, char) => acc + char.charCodeAt(0), 0)
    .toString(16)
    .toUpperCase()
    .padStart(8, '0')

  if (compact) {
    return (
      <div className="flex items-center gap-1.5 px-2 py-0.5 rounded bg-[#00ff88]/10 border border-[#00ff88]/20 text-[9px] font-mono font-bold text-[#00ff88] uppercase tracking-tighter">
        <ShieldCheck size={10} />
        VERIFIED {hash}
      </div>
    )
  }

  return (
    <div className="card p-6 flex flex-col sm:flex-row items-center gap-6 bg-gradient-to-br from-[#00ff88]/5 to-transparent border-[#00ff88]/20">
      <div className="relative flex-shrink-0">
        <div className="absolute inset-0 bg-[#00ff88]/20 blur-xl rounded-full animate-pulse" />
        <ShieldCheck size={48} className="text-[#00ff88] relative z-10" />
      </div>
      <div className="flex-1 text-center sm:text-left">
        <h4 className="text-lg font-black uppercase tracking-tighter mb-1 text-white">Verified Report Snapshot</h4>
        <p className="text-xs leading-relaxed" style={{ color: 'var(--zynthsecure-text)' }}>
          This identifier helps teams reference the report instance that was generated by Zynth for this scan and review cycle.
        </p>
        <div className="mt-3 flex items-center justify-center sm:justify-start gap-2">
           <span className="text-[10px] font-mono text-gray-500 uppercase tracking-widest">Ref: {hash}</span>
           <div className="h-1 w-1 rounded-full bg-gray-700" />
           <span className="text-[10px] font-bold text-[#00ff88] uppercase tracking-widest">Report Logged</span>
        </div>
      </div>
    </div>
  )
}
